### PR TITLE
Remove dependency on deprecated module 'os-homedir'

### PR DESCRIPTION
**Pull request by EightArmCode**

### CODE REVIEW

**Comment by demurgos** [comment]
Hi,
As mentioned in [my other message](https://github.com/tapjs/spawn-wrap/pull/75#issuecomment-416895002), the goal would be to remove it from the `next` branch (not `master`).

I think the only change should be around this line: https://github.com/demurgos/spawn-wrap/blob/74e65280bbbceeecd17d675a2036b0282d7395b6/src/lib/context.ts#L173
(and remove imports/dependency)

**Comment by EightArmCode** [comment]
I see. When do you anticipate this update will be publishable to NPM?

**Comment by demurgos** [comment]
The `next` branch is temporarily published as [demurgos-spawn-wrap](https://www.npmjs.com/package/demurgos-spawn-wrap) (it is used as part of the c8 update).
The c8 update is the main blocker to merge the various forks. There is still a bit of work around the Node API, coverage branches and CLI handling. I'll try to work on this during the week-end. It will definitely be finished by the end of September (hopefully sooner). This fork will then be merged and published on npm as `spawn-wrap` (the goal is not to have a long-lived fork).

**Comment by EightArmCode** [comment]
alright sounds cool. I'll try to get to it today.

**Comment by EightArmCode** [comment]
So sorry I got busy and then have been gone on holiday. Going to create a PR on the next branch now...

**Comment by EightArmCode** [comment]
Alright - I've deleted my fork and re-forked/cloned and it appears that you've already merged my changes. Am I getting that right? The file you mentioned above doesn't seem to exist anymore, and I see my own "git blame" entry in the current version. Do you still need me to do anything with this?

**Comment by demurgos** [comment]
I don't believe I merged it (the `next` branch still uses `os-homedir`).

I prefer to keep the PR open at the moment. I opened many PRs to `spawn-wrap` and other libraries used for code coverage, but the maintainers seem to be busy.

**Comment by demurgos** [comment]
The PRs are starting to get merged to `spawn-wrap`. I'll make sure that this change is included.

**Comment by demurgos** [comment]
Fixed in the main spawn-wrap lib.

**Pull request closed without merging**
